In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [2]:
df =pd.read_csv('Churn_Modelling.csv')
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [4]:
df = pd.get_dummies(df,columns=['Geography','Gender'],dtype=int)
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                0              1            0  
1                  0                1              1            0  
2                  0                0              1            0  
3                  0                0              1            0  
4                  0                1              1            0

In [5]:
x = df.drop('Exited',axis=1)
y = df['Exited']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10,stratify=y)

In [10]:
log_reg = LogisticRegression()
log_reg

LogisticRegression()

In [12]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [14]:
y_pred_test=log_reg.predict(x_test)
y_pred_train=log_reg.predict(x_train)

In [15]:
print(classification_report(y_test,y_pred_test))
print(confusion_matrix(y_test,y_pred_test))
print(accuracy_score(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.98      0.88      1593
           1       0.41      0.06      0.11       407

    accuracy                           0.79      2000
   macro avg       0.60      0.52      0.50      2000
weighted avg       0.72      0.79      0.72      2000

[[1555   38]
 [ 381   26]]
0.7905


In [16]:
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))
print(accuracy_score(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.98      0.88      6370
           1       0.38      0.06      0.10      1630

    accuracy                           0.79      8000
   macro avg       0.59      0.52      0.49      8000
weighted avg       0.72      0.79      0.72      8000

[[6226  144]
 [1540   90]]
0.7895


In [23]:
row= x.iloc[55:56]
row

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
55          619   43       1  125211.92              1          1   

    IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
55               1        113410.49                 1                  0   

    Geography_Spain  Gender_Female  Gender_Male  
55                0              0            1

In [25]:
CreditScore = 619
Age = 43
Tenure = 1
Balance = 125211.92
NumOfProducts = 1
HasCrCard = 1
IsActiveMember = 1
EstimatedSalary = 113410.49
Geography = 'France'
Gender = 'Male'

In [26]:
CreditScore = 619
Age = 43
Tenure = 1
Balance = 125211.92
NumOfProducts = 1
HasCrCard = 1
IsActiveMember = 1
EstimatedSalary = 113410.49
Geography = 'Geography_' + Geography
Gender = 'Gender_' + Gender

In [27]:
columns_name =x.columns.tolist()
columns_name

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Geography_France',
 'Geography_Germany',
 'Geography_Spain',
 'Gender_Female',
 'Gender_Male']

In [33]:
Geography_index = columns_name.index(Geography)
print(Geography_index)
Gender_index = columns_name.index(Gender)
print(Gender_index)

8
12


In [29]:
test_array = np.zeros([1,x.shape[1]])
test_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
test_array[0,0] = CreditScore
test_array[0,1] = Age
test_array[0,2] = Tenure
test_array[0,3] = Balance
test_array[0,4] = NumOfProducts
test_array[0,5] = HasCrCard
test_array[0,6] = IsActiveMember
test_array[0,7] = EstimatedSalary
test_array[0,Geography_index] = 1
test_array[0,Gender_index] = 1

In [35]:
import pickle
import json

In [36]:
with open ('Churn_model.pkl', 'wb') as f:
    pickle.dump(log_reg,f)

In [38]:
project_data = {"Column Names" : columns_name}

with open('proj_data.json','w') as f:
    json.dump(project_data, f)

In [ ]:
CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography,Gender